# Generated by Django 4.1.2 on 2022-10-20 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='robotData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('robotPositionX', models.IntegerField()),
                ('robotPositionY', models.IntegerField()),
            ],
        ),
    ]
